# Dockerfile for Zookeeper server

# Get base ubuntu image
FROM ubuntu:latest

MAINTAINER Matej Pancak <xpanca00@vutbr.cz>

EXPOSE 2181

CMD ["bin/zookeeper-server-start.sh", "config/zookeeper.properties"]

WORKDIR /kafka

COPY src/kafka_2.13-2.7.0 .

RUN apt update
RUN apt install -y openjdk-8-jdk
RUN mkdir /kafka-data
